import Navbar from "@/components/bars/Navbar";
import Provider from "@/providers/SessionProvider";
import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
  params: { session, ...params },
}: {
  children: React.ReactNode;
  params: any;
}) {
  return (
    <html lang="en">
      <Provider session={session}>
        <body className={inter.className}>
          <Navbar />
          <div className=" mt-16 w-5/6 m-auto">{children}</div>
        </body>
      </Provider>
    </html>
  );
}
