# Docs for the Azure Web Apps Deploy action: https://github.com/Azure/webapps-deploy
# More GitHub Actions for Azure: https://github.com/Azure/actions

name: Build and deploy Node.js app to Azure Web App - matteorbprojectcustomer

on:
  push:
    branches:
      - master
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      BASE_URL: ${{ secrets.BASE_URL }}
      NEXTAUTH_URL: ${{ secrets.NEXTAUTH_URL }}
      NEXTAUTH_SECRET: ${{ secrets.NEXTAUTH_SECRET }}
    steps:
      - uses: actions/checkout@v4

      - name: Set up Node.js version
        uses: actions/setup-node@v3
        with:
          node-version: "18.x"
      - name: create env file

        run: |
          touch .env
          echo BASE_URL=$BASE_URL >> .env
          echo NEXTAUTH_URL=$NEXTAUTH_URL >> .env
          echo NEXTAUTH_SECRET=$NEXTAUTH_SECRET >> .env

      - name: npm install, build, and test
        run: |
          npm install
          npm run build --if-present
          npm run test --if-present

      - name: Zip artifact for deployment
        run: zip next.zip ./* .next .env -qr

      - name: "Deploy to Azure Web App"
        id: deploy-to-webapp
        uses: azure/webapps-deploy@v2
        with:
          app-name: "matteorbprojectcustomer"
          publish-profile: ${{ secrets.AZUREAPPSERVICE_PUBLISHPROFILE_EFB68F2171B342C29FCA094B78C4EC7F }}
          package: next.zip
